<?php
define("__HOST__","localhost");
define("__USER__","root");
define("__PASS__","Os@12345");
define("__DB__","php_project");
define("__Debug__Mode__",0);
define("__MAX__NAME__",30);
define("__MAX__USER__NAME__",20);
define("__MAX__PASSWORD__",16);
define("__MIN__PASSWORD__",8);
define("__IMG___EXTENSION__","jpg");
define("__FILE__EXTENSION__","pdf");
define("__RECORDS_PER_PAGE__",2);
